obexd: Remove unused local variables
This fix following build errors:

obexd/src/manager.c: In function ‘get_root’:
obexd/src/manager.c:253:23: error: unused variable ‘os’
    [-Werror=unused-variable]

obexd/src/manager.c: In function ‘manager_emit_transfer_started’:
obexd/src/manager.c:534:22: error: unused variable ‘id’
    [-Werror=unused-variable]

obexd/src/manager.c: In function ‘manager_request_authorization’:
obexd/src/manager.c:684:14: error: unused variable ‘type’
    [-Werror=unused-variable]
obexd/src/manager.c:683:14: error: unused variable ‘filename’
    [-Werror=unused-variable]