DeviceInfo: Fix compilation with old glib
Add missing include glib-compat.h to deviceinfo.c. deviceinfo_free
is using g_slist_free_full() which is not available in old glib
resulting in compilation error.

deviceinfo/deviceinfo.c: In function ‘deviceinfo_free’:
deviceinfo/deviceinfo.c:66: error: implicit declaration of function ‘g_slist_free_full’