Remove unused/broken "echo" RFCOMM plugin
It was disabled for quite some time (since 2009), and does not even
compile anymore if enabled:

plugins/echo.c: In function 'session_event':
plugins/echo.c:53: error: implicit declaration of function
'g_io_channel_read'
plugins/echo.c:57: error: implicit declaration of function
'g_io_channel_write'