monitor: Fix uint64_t format specifier
To be compilable both on 32 and 64 bit architectures the PRIu64 macro
needs to be used as format specifier for uint64_t. Otherwise we'll get
the following type of error either on 32 bit (for %lx) or 64 bit (for
%llx) :

monitor/l2cap.c: In function 'sig_info_rsp':
monitor/l2cap.c:351:3: error: format '%lx' expects argument of type 'long unsigned int', but argument 8 has type 'uint64_t' [-Werror=format]