attrib: Fix "make distcheck" build
Any new header files (att-database.h in this case) need to be added to
Makefile.am.

Fixes this "make distcheck" error:

  CC     attrib/bluetoothd-gatt-service.o
../attrib/gatt-service.c:35:26: fatal error: att-database.h: No such
file or directory
compilation terminated.
make[2]: *** [attrib/bluetoothd-gatt-service.o] Error 1
make[1]: *** [all] Error 2
make: *** [distcheck] Error 1