android/client: Fix build on Android Kitkat
Fix missing kitkat build failure:
external/bluetooth/bluez/android/client/if-hf.c: At top level:
external/bluetooth/bluez/android/client/if-hf.c:108:1: error: unknown
type name 'bthf_wbs_config_t'
external/bluetooth/bluez/android/client/if-hf.c:108:1: error: unknown
type name 'bthf_wbs_config_t'
external/bluetooth/bluez/android/client/if-hf.c: In function
'str2bthf_wbs_config_t':
external/bluetooth/bluez/android/client/if-hf.c:108:1: error:
'bthf_wbs_config_t' undeclared (first use in this function)
external/bluetooth/bluez/android/client/if-hf.c:108:1: note: each
undeclared identifier is reported only once for each function it appears
in
external/bluetooth/bluez/android/client/if-hf.c: At top level:
external/bluetooth/bluez/android/client/if-hf.c:109:2: error:
'BTHF_WBS_NONE' undeclared here (not in a function)
external/bluetooth/bluez/android/client/if-hf.c:110:2: error:
'BTHF_WBS_NO' undeclared here (not in a function)
external/bluetooth/bluez/android/client/if-hf.c:111:2: error:
'BTHF_WBS_YES' undeclared here (not in a function)
make: ***