lib: Add missing includes in bluetooth/hci.h
Compilation fails when using bluetooth/hci.h without other includes.

> /usr/include/bluetooth/hci.h:310:9: error: unknown type name ‘uint8_t’
>   310 |         uint8_t         lap[3];
>       |         ^~~~~~~
> ...
> /usr/include/bluetooth/hci.h:383:9: error: unknown type name ‘bdaddr_t’; did you mean ‘daddr_t’?
>   383 |         bdaddr_t        bdaddr;
>       |         ^~~~~~~~
> ...