sdp: Fix build errors due to unaligned memory access
This fix following compilation errors on ARM.

  CC     lib/sdp.lo
lib/sdp.c: In function 'sdp_device_record_unregister_binary':
lib/sdp.c:2984:11: error: cast increases required alignment of
	target type [-Werror=cast-align]
lib/sdp.c:2984:11: error: cast increases required alignment of
	target type [-Werror=cast-align]
lib/sdp.c: In function 'sdp_device_record_update':
lib/sdp.c:3089:11: error: cast increases required alignment of
	target type [-Werror=cast-align]
lib/sdp.c:3089:11: error: cast increases required alignment of
	target type [-Werror=cast-align]
lib/sdp.c: In function 'sdp_process':
lib/sdp.c:4139:22: error: cast increases required alignment of
	target type [-Werror=cast-align]
lib/sdp.c:4146:14: error: cast increases required alignment of
	target type [-Werror=cast-align]
lib/sdp.c:4146:14: error: cast increases required alignment of
	target type [-Werror=cast-align]
cc1: all warnings being treated as errors
make[1]: *** [lib/sdp.lo] Error 1