lib: Add missing includes in bluetooth/hci_lib.h
Compilation fails when using bluetooth/hci_lib.h without other includes.

/usr/include/bluetooth/hci_lib.h:21:9: error: unknown type name ‘uint16_t’
21 |         uint16_t ogf;
   |         ^~~~~~~~
...
/usr/include/bluetooth/hci_lib.h:182:27: error: ‘HCI_VENDOR_PKT’ undeclared
182 |         hci_set_bit((t == HCI_VENDOR_PKT) ? 0 : (t & HCI_FLT_TYPE_BITS), &f->type_mask);
    |                           ^~~~~~~~~~~~~~