tools/hciattach: Fix missing includes
According to writev manual one should include <sys/uio.h> to use it.

This fix following warnings with bionic:
external/bluetooth/bluez/tools/hciattach_tialt.c: In function
    'texas_load_firmware':
external/bluetooth/bluez/tools/hciattach_tialt.c:142:4: warning:
    implicit declaration of function 'writev'
    [-Wimplicit-function-declaration]
target thumb C: hciattach <= external/bluetooth/bluez/tools/
    hciattach_ath3k.c
target thumb C: hciattach <= external/bluetooth/bluez/tools/
    hciattach_qualcomm.c
external/bluetooth/bluez/tools/hciattach_qualcomm.c: In function
    'qualcomm_load_firmware':
external/bluetooth/bluez/tools/hciattach_qualcomm.c:147:4: warning:
    implicit declaration of function 'writev'
    [-Wimplicit-function-declaration]