obexd/client: Remove unused static functions
This fix following build error:

  CC     obexd/client/obexd-dbus.o
obexd/client/dbus.c:70:13: error: ‘append_array_variant’ defined but
    not used [-Werror=unused-function]
obexd/client/dbus.c:97:13: error: ‘append_dict_variant’ defined but
    not used [-Werror=unused-function]