android: Add missing <string.h> include for memset
Fixes the following build error with clang:
```
../android/client/if-hf-client.c:137:2: error: call to undeclared library function 'memset' with
type 'void *(void *, int, unsigned long)'; ISO C99 and later do not support implicit function
declarations [-Wimplicit-function-declaration]
        memset(features_str, 0, sizeof(features_str));
        ^
../android/client/if-hf-client.c:137:2: note: include the header <string.h> or explicitly provide a declaration for 'memset'
```

Signed-off-by: Marvin Schmidt <marv@exherbo.org>