android: Fix build error with autotools
  CC       android/android_libbt_internal_la-hal_bluetooth.lo
android/hal_bluetooth.c:26:28: fatal error: cutils/sockets.h: No such file or directory
 #include <cutils/sockets.h>
                            ^

Apparently sockets.h is not used for anything, so for now remove it and
once it is actually necessary add local cutils/sockets.h so it can be
build with autotools as well.