android: Fix distcheck build
Add missing monitor/rfcomm.h to android-tester sources. This fix
following build error on make distcheck:

  CC       emulator/android_android_tester-bthost.o
../emulator/bthost.c:40:28: fatal error: monitor/rfcomm.h: No such
    file or directory
 #include "monitor/rfcomm.h"