mgmtops: Add missing compatibility header include
glib-compat.h needs to be included when either g_slist_free_full() or
g_list_free_full() is used on a C file. Otherwise, it will fail to build
on older (supported) Glib versions that lack these functions.

Fixes this build error on GLib 2.24.1:

plugins/mgmtops.c: In function ‘remove_controller’:
plugins/mgmtops.c:180: error: implicit declaration of function
‘g_slist_free_full’