emulator: Add missing <limits.h> include for PATH_MAX
Fixes the following build error with musl libc:
```
emulator/vhci.c:282:16: error: use of undeclared identifier 'PATH_MAX'
        char filename[PATH_MAX];
                      ^
1 error generated.
```

Signed-off-by: Marvin Schmidt <marv@exherbo.org>