android: Fix build errors due to missing headers
In file included from ./android/hardware/bluetooth.h:24:0,
                 from android/hal_bt_sock.c:20:
./android/hardware/hardware.h:23:34: fatal error: cutils/native_handle.h: No such file or directory
 #include <cutils/native_handle.h>
                                  ^
In file included from ./android/hardware/bluetooth.h:24:0,
                 from android/hal_bluetooth.c:23:
./android/hardware/hardware.h:23:29: fatal error: system/graphics.h: No such file or directory
 #include <system/graphics.h>
                             ^