tests/example-gatt-client: Fix using invalid property
This fixes the following trace caused by GattServices1 no longer
containing a property called Characteristics:

Traceback (most recent call last):
  File "./example-gatt-client", line 221, in <module>
    main()
  File "./example-gatt-client", line 207, in main
    if not process_hr_service(service_path):
  File "./example-gatt-client", line 167, in process_hr_service
    chrc_paths = service_props['Characteristics']
KeyError: 'Characteristics'