unit: Replace g_test_fail() with g_assert_not_reached()
g_test_fail() is introduced in Glib v2.30 and we are using Glib v2.28 as
the minimum requirement for the build. This patch resolves the
compilation error that happen with Glib v2.28.

Error log:
  CC     unit/test-mgmt.o
unit/test-mgmt.c: In function ‘check_actions’:
unit/test-mgmt.c:100:2: error: implicit declaration of
    function ‘g_test_fail’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[1]: *** [unit/test-mgmt.o] Error 1
make: *** [all] Error 2