tools: Fix build-error on 32-bit systems
The %zX format specifier for st_size causes the following warning:

tools/create-image.c:120:5: error: format ‘%zX’ expects argument of type ‘size_t’, but argument 10 has type ‘__off_t’ [-Werror=format=]
      st.st_size, 0, 0, 0, 0, namelen + 1, 0, name);
      ^

The best way to solve this (as off_t doesn't have a standard format
specifier) is to use 'j' and do a typecast to uintmax_t.