obexd/MAP: Fix protected property value
"Sent" flag value was returned instead of "Protected" one.
This also fix following build error:

  CC     obexd/client/obexd-map.o
obexd/client/map.c:711:17: error: ‘get_protected’ defined but not
    used [-Werror=unused-function]
cc1: all warnings being treated as errors