tools: Fix compilation errors with musl
This fix number of includes for <sys/poll.h> instead of <poll.h>

  CC       tools/hciattach.o
In file included from tools/hciattach.c:41:0:
/usr/include/sys/poll.h:1:2: error: #warning redirecting incorrect
   #include <sys/poll.h> to <poll.h> [-Werror=cpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^