lib: Fix compilation error in C++ due to inline function
This adds explicit typecasts to an inline function to make it C++
compatible. What follows is a sample error message from g++ when
compiling without this patch.

/usr/include/bluetooth/bluetooth.h:
  In function 'void bswap_128(const void*, void*)':
/usr/include/bluetooth/bluetooth.h:348:21:
  error: invalid conversion from 'const void*' to 'const uint8_t*
         {aka const unsigned char*}' [-fpermissive]
  const uint8_t *s = src;