sdpd-request: Fix build errors due to unaligned memory access
This fix following compilation errors on ARM.

  CC     src/bluetoothd-sdpd-request.o
src/sdpd-request.c: In function ‘extract_des’:
src/sdpd-request.c:186:17: error: cast increases required alignment of
	target type [-Werror=cast-align]
src/sdpd-request.c:186:17: error: cast increases required alignment of
	target type [-Werror=cast-align]
src/sdpd-request.c:210:17: error: cast increases required alignment of
	target type [-Werror=cast-align]
src/sdpd-request.c:210:17: error: cast increases required alignment of
	target type [-Werror=cast-align]
cc1: all warnings being treated as errors
make[1]: *** [src/bluetoothd-sdpd-request.o] Error 1