build: Check if explicit_bzero is missing
This check gets around the redefinition of explicit_bzero in ELL

In file included from ell/random.c:34:0:
ell/missing.h:59:20: error: static declaration of ‘explicit_bzero’ follows non-static declaration
 static inline void explicit_bzero(void *s, size_t n)
                    ^~~~~~~~~~~~~~
In file included from ./ell/util.h:26:0,
                 from ell/private.h:26,
                 from ell/random.c:33:
/usr/include/string.h:435:13: note: previous declaration of ‘explicit_bzero’ was here
 extern void explicit_bzero (void *__s, size_t __n) __THROW __nonnull ((1));
             ^~~~~~~~~~~~~~