hciemu: Fix strict-aliasing rules handling
gcc 4.4.3 (from Ubuntu 10.04) started complaining about this code:

test/hciemu.c: In function ‘hci_host_control’:
test/hciemu.c:431: error: dereferencing pointer ‘({anonymous})’ does break
strict-aliasing rules
test/hciemu.c:431: note: initialized from here

The fix is based on commit 97046eaf3fc44b4451157b1a1bbc166ab0f4dda8.