test/example-gatt-server: Fix error on Property.GetAll
get_properties is a method not a dictionary which cause the following
error:
  TypeError: 'method' object is not subscriptable