build: Fix checking result of sizeof instead of memcmp
This can be easily spot when building with clang:

emulator/smp.c:373:53: error: size argument in 'memcmp' call is a comparison
      [-Werror,-Wmemsize-comparison]
        if (memcmp(conn->pcnf, confirm, sizeof(conn->pcnf) != 0)) {

tools/smp-tester.c:596:53: error: size argument in 'memcmp' call is a comparison
      [-Werror,-Wmemsize-comparison]
        if (memcmp(data->pcnf, confirm, sizeof(data->pcnf) != 0)) {