error: Add helper to return DbusMessage errors from errno
This will allow us to start adding more precise errors instead of
"Failed" with a string if we're parsing an errno.