monitor: Add missing include
Bionic library requires explicit include for data types used in ioctl
call. This fix following build error with bionic:

target  C: btmon <= external/bluetooth/bluez/monitor/display.c
external/bluetooth/bluez/monitor/display.c: In function 'num_columns':
external/bluetooth/bluez/monitor/display.c:59:18: error: storage size
    of 'ws' isn't known