build: Bump D-Bus dependency to 1.6
dbus_validate_path() was introduced in D-Bus 1.6 and it is no longer
possible to build with 1.4.

 CCLD   tools/bluetooth-player
tools/bluetooth-player.o: In function `cmd_change_folder':
tools/bluetooth-player.c:741: undefined reference to `dbus_validate_path'
collect2: ld returned 1 exit status